# Generated by Django 4.0 on 2022-01-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0004_alter_ordermodel_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='email',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
