# Generated by Django 4.0 on 2022-01-04 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0005_alter_ordermodel_contact_alter_ordermodel_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_paid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
