# Generated by Django 4.0 on 2022-01-04 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0006_ordermodel_is_paid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordermodel',
            old_name='is_paid',
            new_name='payment',
        ),
    ]
