# Generated by Django 4.0 on 2022-01-05 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0007_rename_is_paid_ordermodel_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='payment',
            field=models.BooleanField(default=False),
        ),
    ]
