# Generated by Django 4.0 on 2022-01-11 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0009_alter_ordermodel_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='created_on',
        ),
    ]
