# Generated by Django 4.0 on 2022-08-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0010_remove_ordermodel_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='delivered',
            field=models.BooleanField(default=False),
        ),
    ]
