# Generated by Django 4.0 on 2022-08-23 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Customer', '0011_ordermodel_delivered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='delivered',
        ),
    ]
